apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
   name: mysql-storage
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mysql
    server: nfs01
